---
- name: Stop and fully remove nginx on agent servers
  hosts: agent_servers
  gather_facts: true
  become: true
  vars_files:
    - vars/agents.yaml
    - vars/vault.yaml   # remove this line if you’re not actually using vault vars

  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: true

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Stop nginx if present
      ansible.builtin.service:
        name: "{{ package_service }}"
        state: stopped
        enabled: false
      when: "'{{ package_service }}.service' in services"

    # Purge all likely nginx packages (unit usually comes from nginx-core/common)
    - name: Purge nginx packages (meta + variants)
      ansible.builtin.apt:
        name:
          - nginx
          - nginx-core
          - nginx-common
          - nginx-full
          - nginx-light
          - nginx-extras
        state: absent
        purge: true
        autoremove: true

    # Best-effort catch-all
    - name: Purge any remaining nginx* packages
      ansible.builtin.apt:
        name: "nginx*"
        state: absent
        purge: true
        autoremove: true
      ignore_errors: true

    # Remove stray unit/drop-in files if they exist
    - name: Remove nginx systemd unit and drop-ins if present
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/systemd/system/nginx.service
        - /etc/systemd/system/nginx.service.d
        - /lib/systemd/system/nginx.service
        - /usr/lib/systemd/system/nginx.service
      ignore_errors: true

    # Clean up configs/logs (optional)
    - name: Remove nginx config and logs
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx
        - /var/log/nginx
      ignore_errors: true

    # Refresh systemd
    - name: Reset failed units
        # not idempotent—avoid marking changed/fail
      ansible.builtin.command: systemctl reset-failed
      changed_when: false
      failed_when: false

    - name: Reload systemd units
      ansible.builtin.command: systemctl daemon-reload
      changed_when: false

    # Verify (won’t fail the play)
    - name: Check nginx status (expect 'Unit nginx.service could not be found')
      ansible.builtin.command: systemctl status nginx
      register: nginx_status
      changed_when: false
      failed_when: false

    - name: Show nginx status result
      ansible.builtin.debug:
        var: nginx_status.stdout_lines

